apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  namespace: talk-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: mongo:4
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-data
          mountPath: ./data/mongo:/data/db
      volumes:
      - name: mongo-data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: talk-ns
spec:
  type: ClusterIP
  ports:
    - port: 27017
  selector:
    app: mongo
